version: '3'

services:
  jenkins-bot:
    build: .
    image: pt-jenkins
    container_name: 'pt-jenkins'
    ports:
      - 7123:7123
    volumes:
      - defaultLog:/app/logs
      - jenkinsData:/app/data

volumes:
  defaultLog:
  jenkinsData:
